# Generated by Django 2.2 on 2019-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='default.png', upload_to='announcement_pics'),
        ),
        migrations.AddField(
            model_name='intro',
            name='image',
            field=models.ImageField(default='default.png', upload_to='intro_pics'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.png', upload_to='news_pics'),
        ),
    ]
