# Generated by Django 2.2 on 2019-04-21 08:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190421_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='announcement_pics/default.png', upload_to='announcement_pics'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(default='intro_pics/default.png', upload_to='intro_pics'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_pics/default.png', upload_to='news_pics'),
        ),
    ]
