# Generated by Django 2.2 on 2019-04-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190421_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='intro_pics/default.png', upload_to='intro_pics')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
    ]
