# Generated by Django 2.2 on 2019-04-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190422_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='teacher_photos/default.png', upload_to='teacher_photos')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
