# Generated by Django 2.2 on 2019-04-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='table_type',
            field=models.CharField(choices=[('general', 'general'), ('extra', 'extra')], default='general', max_length=25),
        ),
    ]
