# Generated by Django 2.2 on 2019-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190423_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='post_type',
            field=models.CharField(choices=[('welcome', 'welcome'), ('history', 'history')], default='welcome', max_length=25),
        ),
    ]
