# Generated by Django 2.2 on 2019-04-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_about_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('information', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='table',
            field=models.ImageField(upload_to='schedule_tables'),
        ),
    ]
