# Generated by Django 2.2 on 2019-05-01 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
