# Generated by Django 2.2 on 2019-05-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gallery_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default=None, upload_to='about_pics'),
        ),
    ]
