# Generated by Django 2.2 on 2019-05-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190511_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='about_pics'),
        ),
    ]
