# Generated by Django 2.2 on 2019-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190511_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('table_type', models.CharField(choices=[('general_summer', 'general_summer'), ('general_winter', 'general_winter'), ('extra', 'extra')], default='general_summer', max_length=25)),
                ('table', models.TextField()),
            ],
        ),
    ]
