# Generated by Django 2.2 on 2019-05-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attachedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='news',
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='teacher',
        ),
    ]
