# Generated by Django 2.2 on 2019-05-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190512_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfile',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_files', to='core.Event'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_files', to='core.News'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='teacher_files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_files', to='core.Teacher'),
        ),
    ]
