# Generated by Django 2.2 on 2019-05-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190512_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFileAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attached_files')),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_files', to='core.About')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attached_files')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_files', to='core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFileNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attached_files')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_files', to='core.News')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFileTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attached_files')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_files', to='core.Teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='AttachedFile',
        ),
    ]
