# Generated by Django 2.2 on 2019-05-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190514_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfileabout',
            name='name',
            field=models.CharField(default='Download', max_length=300),
        ),
        migrations.AddField(
            model_name='attachedfileevent',
            name='name',
            field=models.CharField(default='Download', max_length=300),
        ),
        migrations.AddField(
            model_name='attachedfilenews',
            name='name',
            field=models.CharField(default='Download', max_length=300),
        ),
        migrations.AddField(
            model_name='attachedfileteacher',
            name='name',
            field=models.CharField(default='Download', max_length=300),
        ),
    ]
