# Generated by Django 2.2 on 2019-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190517_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'home'), ('about', 'about'), ('gallery', 'gallery'), ('schedule', 'schedule'), ('students', 'students'), ('news', 'news')], default='home', max_length=25)),
                ('image', models.ImageField(default=None, upload_to='backgrounds')),
            ],
        ),
    ]
