# Generated by Django 2.2 on 2019-06-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('management', 'management'), ('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=25),
        ),
        migrations.AlterField(
            model_name='attachedfileabout',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
