# Generated by Django 2.2 on 2019-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_galleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
