# Generated by Django 2.2 on 2019-06-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190612_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default=None, upload_to='student_item_pics')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='attachedfileevent',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='attachedfilenews',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='attachedfileteacher',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='AttachedFileStudentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attached_files')),
                ('name', models.CharField(max_length=300)),
                ('student_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_item_files', to='core.StudentItem')),
            ],
        ),
    ]
