# Generated by Django 2.2 on 2019-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190612_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='post_type',
            field=models.CharField(choices=[('welcome', 'welcome'), ('info', 'info')], default='info', max_length=25),
        ),
    ]
