# Generated by Django 2.2.2 on 2019-06-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFileAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attached_files')),
                ('name', models.CharField(max_length=300)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_files', to='core.Student')),
            ],
        ),
    ]
